### ISSUE TITLE
Weather not updating in Fitbit Versa device 

### ISSUE THREAD

**Issue by maneesh2780** [gregoiresage/fitbit-weather#11]
What is API key ??

**Comment by Samurai016** [comment]
*API key* is the key that the weather provider gives you. The library seems to support OpenWeatherMap, DarkSky and WeatherBit.

### DarkSky
DarkSky no longer accept signups for their API, because it was bought by Apple.

### OpenWeatherMap
[Go here](https://openweathermap.org/price), select a plan and signup to it, then in the dashboard you will get the API key.

### WeatherBit
[Go here](https://www.weatherbit.io/pricing), select a plan and signup to it, then in the dashboard you will get the API key.
